---
title: "Generating The Figures"
author: "Sina Aghaei"
date: "10/24/2020"
output: 
  # flexdashboard::flex_dashboard:
  #   orientation: columns
  html_document:
    # number_sections: true
 
---


In this script we provide the code for generating the figures in the paper.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE,warning = FALSE )
library(kableExtra)
library(png)
library(ggplot2)
library(reshape2)
library(egg)
require(tidyr)
require(dplyr)
library(dplyr)
library(latex2exp)
# library(ggpubr)
library(data.table)
library(RColorBrewer)
library(MASS)
require(scales)
rm(list=ls())

data_train= read.csv('./../res41.csv', header=TRUE, sep=',', na.strings="", stringsAsFactors =TRUE) 

forpres=FALSE
if (forpres){
  fontfam = "sans"
} else {
  fontfam = "serif"
}

figure_path = "./"


data_train$sample <- as.factor(data_train$sample)
data_train$depth <- as.factor(data_train$depth)

```


# 
```{r echo=TRUE, warning=FALSE}
tmp  <- data_train
index <- tmp$fair.bound == 0
tmp$fair.bound[index] = 1

tmp <- tmp %>%
  group_by(approach,data,depth, fair.type, fair.bound) %>%
  summarise(mean(train.acc),mean(sp.train.data), mean(sp.train.pred))

names(tmp) <- c("approach","data","depth","fair.type","fair.bound","train.acc","train.data.sp","train.pred.sp")

g1 <- ggplot(data = subset(tmp, tmp$depth==2), aes(x=fair.bound)) +
  geom_line( aes(y=train.acc), size=2, color=brewer.pal(4, 'Set1')[3]) + 
  geom_line( aes(y=train.pred.sp), size=2, color=brewer.pal(4, 'Set1')[2]) +
  scale_y_continuous(
    # Features of the first axis
    name = "Train Acc",
    # Add a second axis and specify its features
    sec.axis = sec_axis(~.*1, name="Train SP")
  ) +
  theme(legend.position = "right",text = element_text(size=14,family=fontfam)) 
print(g1)

if (forpres)
{
  ggsave(paste(figure_path,"sp.pdf",sep = ""),device = "pdf", width = 5, height = 3.3, units =  "in")
} else {
  ggsave(paste(figure_path,"sp.pdf",sep = ""),device = "pdf", width = 5, height = 3.3, units =  "in")
}

```
