---
title: "Generating The Figures"
author: "Sina Aghaei"
date: "10/24/2020"
output: 
  # flexdashboard::flex_dashboard:
  #   orientation: columns
  html_document:
    # number_sections: true
 
---


In this script we provide the code for generating the figures in the paper.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE,warning = FALSE )
library(kableExtra)
library(png)
library(ggplot2)
library(reshape2)
library(egg)
require(tidyr)
require(dplyr)
library(dplyr)
library(latex2exp)
# library(ggpubr)
library(data.table)
library(RColorBrewer)
library(MASS)
require(scales)
rm(list=ls())
library(extrafont)

fontfam = "sans" #sans serif
data_name = 'german'
```

#Preparing Data

```{r echo=TRUE, warning=FALSE}
prepare <- function (data) {
  tmp <- data[,c("approach",'sample',"depth","fair.bound","train.acc",'test.acc',
                     "sp.train.pred","sp.test.pred")]
  
  tmp <- tmp %>%
    group_by(approach,depth, fair.bound) %>%
    summarise(mean(train.acc),mean(test.acc), mean(sp.train.pred),
              mean(sp.test.pred))
  
  names(tmp) <- c("approach","depth","fair.bound","train.acc",'test.acc',
                     "train.disc","test.disc")
  
  tmp$fair.bound <- as.numeric(as.character(tmp$fair.bound))
  
  
  tmp1 <- tmp[,c("approach","depth","fair.bound","test.acc","test.disc")]
  tmp1$source <- 'out-of-sample'
  names(tmp1) <- c("approach","depth","fair.bound","acc","disc",'source')
  tmp2 <- tmp[,c("approach","depth","fair.bound","train.acc","train.disc")]
  tmp2$source <- 'in-sample'
  names(tmp2) <- c("approach","depth","fair.bound","acc","disc",'source')
  tmp <- rbind(tmp1,tmp2)
  rm(tmp1,tmp2)
  
  
  tmp
}
```

```{r echo=TRUE, warning=FALSE}

if(data_name == 'adult'){
  file_address = './../Results/EAAMO/Flow_KamiranVersion_warm (April 19)/calib 0/FlowKamiran_warm_limited-adult-2_d3_calib_0.csv'
}else if(data_name == 'compas'){
  file_address = './../Results/EAAMO/Flow_KamiranVersion_warm (April 19)/calib 0/FlowKamiran_warm_compas_d3_calib_0.csv'
}else if(data_name == 'german'){
  file_address = './../Results/EAAMO/Flow_KamiranVersion_warm (April 19)/calib 0/FlowKamiran_warm_german_d3_calib_0.csv'
} 

data= read.csv(file_address, header=FALSE, sep=',', na.strings="", stringsAsFactors =TRUE) 
header= read.csv('./../header_kamiran.csv', header=TRUE, sep=',', na.strings="", stringsAsFactors =TRUE) 

names(data) <- names(header)
rm(header)




data$sample <- as.factor(data$sample)
# data$depth <- as.factor(data$depth)
data$fair.type <- as.factor(data$fair.type)
data$fair.bound <- as.factor(data$fair.bound)


tmp_none <- data[data$fair.type == 'None',]
tmp_none$fair.type = 'SP'
data = rbind(data,tmp_none)

data <- data[data$fair.type!= 'None',]
data$fair.type <- droplevels(data$fair.type)
rm(tmp_none)
```

#Preparing Data

```{r echo=TRUE, warning=FALSE}
data_flow <- prepare(data) 
data_flow$approach <- "FairOCT"
```

# Reading and preparing the kamiran's results

```{r echo=TRUE, warning=FALSE}
################################################## (IGC).Relab
if(data_name == 'adult'){
  file_address = './../Results/EAAMO/Kamiran/no_tuning/final/igc_relab/adult.csv'
}else if(data_name == 'compas'){
  file_address = './../Results/EAAMO/Kamiran/no_tuning/final/igc_relab/compas.csv'
}else if(data_name == 'german'){
  file_address = './../Results/EAAMO/Kamiran/no_tuning/final/igc_relab/german.csv'
}

data= read.csv(file_address, header=FALSE, sep=',', na.strings="", stringsAsFactors =TRUE) 
header= read.csv('./../Results/EAAMO/Kamiran/no_tuning/header.csv', header=TRUE, sep=',', na.strings="", stringsAsFactors =TRUE) 
names(data) <- names(header)
rm(header)

data$depth <- data$depth + 1
data$approach <- 'IGC_Relab'

data <- data[,c('approach',"sample",'fair.bound','depth','train.acc','sp.train.pred','test.acc','sp.test.pred')]

data_kamiran_1 <- prepare(data)
rm(data)
data_kamiran_1$acc <- data_kamiran_1$acc/100

################################################## (IGC-IGS).Relab
if(data_name == 'adult'){
  file_address = './../Results/EAAMO/Kamiran/no_tuning/final/igc-igs_relab/adult.csv'
}else if(data_name == 'compas'){
  file_address = './../Results/EAAMO/Kamiran/no_tuning/final/igc-igs_relab/compas.csv'
}else if(data_name == 'german'){
  file_address = './../Results/EAAMO/Kamiran/no_tuning/final/igc-igs_relab/german.csv'
}

data= read.csv(file_address, header=FALSE, sep=',', na.strings="", stringsAsFactors =TRUE) 
header= read.csv('./../Results/EAAMO/Kamiran/no_tuning/header.csv', header=TRUE, sep=',', na.strings="", stringsAsFactors =TRUE) 
names(data) <- names(header)
rm(header)

data$depth <- data$depth + 1
data$approach <- 'IGC-IGS_Relab'

data <- data[,c('approach',"sample",'fair.bound','depth','train.acc','sp.train.pred','test.acc','sp.test.pred')]

data_kamiran_2 <- prepare(data)
rm(data)
data_kamiran_2$acc <- data_kamiran_2$acc/100

################################################## (IGC+IGS).Relab
if(data_name == 'adult'){
  file_address = './../Results/EAAMO/Kamiran/no_tuning/final/igc+igs_relab/adult.csv'
}else if(data_name == 'compas'){
  file_address = './../Results/EAAMO/Kamiran/no_tuning/final/igc+igs_relab/compas.csv'
}else if(data_name == 'german'){
  file_address = './../Results/EAAMO/Kamiran/no_tuning/final/igc+igs_relab/german.csv'
}

data= read.csv(file_address, header=FALSE, sep=',', na.strings="", stringsAsFactors =TRUE) 
header= read.csv('./../Results/EAAMO/Kamiran/no_tuning/header.csv', header=TRUE, sep=',', na.strings="", stringsAsFactors =TRUE) 
names(data) <- names(header)
rm(header)

data$depth <- data$depth + 1
data$approach <- 'IGC+IGS_Relab'

data <- data[,c('approach',"sample",'fair.bound','depth','train.acc','sp.train.pred','test.acc','sp.test.pred')]

data_kamiran_3 <- prepare(data)
rm(data)
data_kamiran_3$acc <- data_kamiran_3$acc/100
```


```{r echo=TRUE, warning=FALSE}
data <- rbind(data_flow, data_kamiran_1, data_kamiran_2,data_kamiran_3)
data <- subset(data, data$fair.bound %in% data_kamiran_3$fair.bound)

data$approach <- as.factor(data$approach)
data$approach<- factor(data$approach, levels = c('FairOCT','IGC_Relab','IGC-IGS_Relab','IGC+IGS_Relab'))
```

# Plotting


## Defualt

```{r echo=TRUE, warning=FALSE}

default_plot<- function(data, t_source, t_depth){
  tmp <- subset(data,data$depth ==t_depth & data$source == t_source) 
  x_title = ""
  y_title= ""
  
  g1 <- ggplot(tmp,aes(x=((disc))*100, y=acc*100)) +
      geom_line(aes(linetype=approach), size=3) + 
      geom_point(aes(color = fair.bound),size=10)+
      scale_color_gradient(low="blue", high="red")+
      scale_linetype_manual(values=c(1,3,2,4))+
      labs(x=x_title, y = y_title, linetype = "Approach", color ='SP Bound')+
      # xlim(-7, 17)+#all
      #xlim(-7, 12.5)+#limited-adult
      # xlim(0, 17)+#compas
      # xlim(-2, 9)+#german
      ylim(50, 85)+
      theme(
        # plot.title = element_text(size = 25),
        axis.text = element_text(size = 45),
        legend.position = "right", legend.key.size = unit(2, "cm"),
        legend.text = element_text(size = 30),
        legend.title = element_text(size = 35),
        text = element_text(family=fontfam),
        axis.title = element_text(size = 40)
      ) 
  
  figure_path = "./EAAMO/no calibration d2&3/default/"
  fig_name = paste('no_calibration_',data_name,'_depth_',t_depth,'_', t_source,'.pdf', sep = '')
  
  ggsave(paste(figure_path,fig_name,sep = ""),device = "pdf", width = 16, height = 12, units =  "in")#width = 12, height = 8
}
```


## No circles

```{r echo=TRUE, warning=FALSE}

no_circles_plot<- function(data, t_source, t_depth){
  tmp <- subset(data,data$depth ==t_depth & data$source == t_source) 
  x_title = ""
  y_title= ""
  
  g1 <- ggplot(tmp,aes(x=((disc))*100, y=acc*100)) +
      geom_line(aes(linetype=approach,colour=approach), size=3) + 
      geom_point(size=3)+
      scale_linetype_manual(values=c(1,3,2,4))+
      labs(x=x_title, y = y_title, color  = 'Approach', linetype = 'Approach')+
      # xlim(-7, 17)+#all
      #xlim(-7, 12.5)+#limited-adult
      # xlim(0, 17)+#compas
      # xlim(-2, 9)+#german
      ylim(50, 85)+
      theme(
        # plot.title = element_text(size = 25),
        axis.text = element_text(size = 45),
        legend.position = "right", legend.key.size = unit(2, "cm"),
        legend.text = element_text(size = 30),
        legend.title = element_text(size = 35),
        text = element_text(family=fontfam),
        axis.title = element_text(size = 40)
      ) 
  
  figure_path = "./EAAMO/no calibration d2&3/no circles/"
  fig_name = paste('no_calibration_',data_name,'_depth_',t_depth,'_', t_source,'.pdf', sep = '')
  
  ggsave(paste(figure_path,fig_name,sep = ""),device = "pdf", width = 16, height = 12, units =  "in")#width = 12, height = 8
}
```


## different point shapes per approach

```{r echo=TRUE, warning=FALSE}

diff_point_shapes_plot<- function(data, t_source, t_depth){
  tmp <- subset(data,data$depth ==t_depth & data$source == t_source) 
  x_title = ""
  y_title= ""
  
  g1 <- ggplot(tmp,aes(x=((disc))*100, y=acc*100)) +
      geom_line(aes(linetype=approach), size=3) + 
      geom_point(aes(color = fair.bound,shape = approach),size=10)+
      scale_color_gradient(low="blue", high="red")+
      scale_linetype_manual(values=c(1,3,2,4))+
      scale_shape_manual(values=c(15, 16, 17,18))+
      labs(x=x_title, y = y_title, color  = 'SP Bound', linetype = 'Approach', shape = 'Approach')+
      # xlim(-7, 17)+#all
      #xlim(-7, 12.5)+#limited-adult
      # xlim(0, 17)+#compas
      # xlim(-2, 9)+#german
      ylim(50, 85)+
      theme(
        # plot.title = element_text(size = 25),
        axis.text = element_text(size = 45),
        legend.position = "right", legend.key.size = unit(2, "cm"),
        legend.text = element_text(size = 30),
        legend.title = element_text(size = 35),
        text = element_text(family=fontfam),
        axis.title = element_text(size = 40)
      ) 
  
  figure_path = "./EAAMO/no calibration d2&3/different point shapes per approach/"
  fig_name = paste('no_calibration_',data_name,'_depth_',t_depth,'_', t_source,'.pdf', sep = '')
  
  ggsave(paste(figure_path,fig_name,sep = ""),device = "pdf", width = 16, height = 12, units =  "in")#width = 12, height = 8
}
```



```{r echo=TRUE, warning=FALSE}
for(t in c(2,3)){
  default_plot(data, 'in-sample',t)
  default_plot(data, 'out-of-sample',t)
  
  no_circles_plot(data, 'in-sample',t)
  no_circles_plot(data, 'out-of-sample',t)
  
  diff_point_shapes_plot(data, 'in-sample',t)
  diff_point_shapes_plot(data, 'out-of-sample',t)
}




```



