---
title: "Generating The Figures"
author: "Sina Aghaei"
date: "10/24/2020"
output: 
  # flexdashboard::flex_dashboard:
  #   orientation: columns
  html_document:
    # number_sections: true
 
---


In this script we provide the code for generating the figures in the paper.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE,warning = FALSE )
library(kableExtra)
library(png)
library(ggplot2)
library(reshape2)
library(egg)
require(tidyr)
require(dplyr)
library(dplyr)
library(latex2exp)
# library(ggpubr)
library(data.table)
library(RColorBrewer)
library(MASS)
require(scales)
rm(list=ls())



data= read.csv('./../Results/Dec 29/FlowOCT/FlowOCT_limited-adult-2.csv', header=FALSE, sep=',', na.strings="", stringsAsFactors =TRUE) 
data_name = 'limited-adult-2'
header= read.csv('./../header.csv', header=TRUE, sep=',', na.strings="", stringsAsFactors =TRUE) 

names(data) <- names(header)
rm(header)

fontfam = "sans" #sans serif

figure_path = "./"



data$sample <- as.factor(data$sample)
data$depth <- as.factor(data$depth)
data$fair.type <- as.factor(data$fair.type)
data$fair.bound <- as.factor(data$fair.bound)


for(i in c('SP','PE','EOpp','EOdds')){#'SP','CSP','PE','EOpp','EOdds'
  tmp_none <- data[data$fair.type == 'None',]
  tmp_none$fair.type = i
  data = rbind(data,tmp_none)
}

data <- data[data$fair.type!= 'None',]
data$fair.type <- droplevels(data$fair.type)
rm(tmp_none)

data$data <- data_name
```

#Preparing Data
```{r echo=TRUE, warning=FALSE}
tmp <- data

tmp <- tmp %>%
  group_by(approach,data,depth, fair.type, fair.bound) %>%
  summarise(mean(train.acc),mean(test.acc),mean(sp.train.data), mean(sp.train.pred),
            mean(sp.test.data),mean(sp.test.pred),
            mean(csp.train.data), mean(csp.train.pred),
            mean(csp.test.data),mean(csp.test.pred),
            mean(pe.train.pred),
            mean(pe.test.pred),
            mean(EOpp.train.pred),
            mean(EOpp.test.pred),
            mean(EOdds.train.pred),
            mean(EOdds.test.pred))

names(tmp) <- c("approach","data","depth","fair.type","fair.bound","train.acc",'test.acc',
                   "train.data.sp","train.pred.sp","test.data.sp","test.pred.sp",
                   "train.data.csp","train.pred.csp","test.data.csp","test.pred.csp",
                   "train.pred.pe","test.pred.pe",
                   "train.pred.EOpp","test.pred.EOpp",
                   "train.pred.EOdds","test.pred.EOdds")


for(m in c('SP','PE','EOpp','EOdds')){
  metric = m
  if(metric == 'SP'){
  tmp2 <- subset(tmp, tmp$fair.type == metric)
  tmp2 <- tmp2[c("approach","data","depth","fair.type","fair.bound","test.acc",'train.acc',
             'test.pred.sp','train.pred.sp')]
  
x_title = ''#"Statistical Parity (%)"
y_title= ''#"Accuracy (%)"
legend_title = 'SP Bound'

}else if(metric == 'CSP'){
  tmp2 <- subset(tmp, tmp$fair.type == metric)
  tmp2 <- tmp2[c("approach","data","depth","fair.type","fair.bound","test.acc",'train.acc',
             'test.pred.csp','train.pred.csp')]
  
  x_title = ''#"Conditional Statistical Parity (%)"
  y_title= ''#"Accuracy (%)"
  legend_title = 'CSP Bound'
}else if(metric == 'PE'){
  tmp2 <- subset(tmp, tmp$fair.type == metric)
  tmp2 <- tmp2[c("approach","data","depth","fair.type","fair.bound","test.acc",'train.acc',
             'test.pred.pe','train.pred.pe')]
  
  x_title = ''#"Predictive Equality (%)"
  y_title= ''#"Accuracy (%)"
  legend_title = 'PE Bound'
}else if(metric == 'EOpp'){
  tmp2 <- subset(tmp, tmp$fair.type == metric)
  tmp2 <- tmp2[c("approach","data","depth","fair.type","fair.bound","test.acc",'train.acc',
             'test.pred.EOpp','train.pred.EOpp')]
  
  x_title = ''#"Equal Opportunity (%)"
  y_title= ''#"Accuracy (%)"
  legend_title = 'EOpp Bound'
}else if(metric == 'EOdds'){
  tmp2 <- subset(tmp, tmp$fair.type == metric)
  tmp2 <- tmp2[c("approach","data","depth","fair.type","fair.bound","test.acc",'train.acc',
             'test.pred.EOdds','train.pred.EOdds')]
  
  x_title = ''#"Equalized Odds (%)"
  y_title= ''#"Accuracy (%)"
  legend_title = 'EOdds Bound'
}


names(tmp2) <- c("approach","data","depth","fair.type","fair.bound","test.acc","train.acc","test.pred.disc","train.pred.disc")
# tmp$fair.type <- factor(tmp$fair.type, levels = c('SP','CSP','PE','EOpp','EOdds'))
tmp2$fair.bound <- as.numeric(as.character(tmp2$fair.bound))


tmp2_1 <- tmp2[,c("approach","data","depth","fair.type","fair.bound","test.acc","test.pred.disc")]
tmp2_1$source <- 'out-of-sample'
names(tmp2_1) <- c("approach","data","depth","fair.type","fair.bound","acc","disc",'source')
tmp2_2 <- tmp2[,c("approach","data","depth","fair.type","fair.bound","train.acc","train.pred.disc")]
tmp2_2$source <- 'in-sample'
names(tmp2_2) <- c("approach","data","depth","fair.type","fair.bound","acc","disc",'source')
tmp2 <- rbind(tmp2_1,tmp2_2)
rm(tmp2_1,tmp2_2)

t_depth = 2
g1 <- ggplot(data = subset(tmp2,tmp2$depth == t_depth),aes(x=(disc)*100, y=acc*100)) +
  geom_line(aes(linetype=source), size=3) + 
  geom_point(aes(color = fair.bound),size=10)+
  scale_color_gradient(low="blue", high="red")+
  labs(x=x_title, y = y_title, linetype = "Data", color =legend_title)+
  # coord_flip(clip = "off") +
  # xlim(0, 35)+#compas
  # ylim(50, 70)+#compas
  xlim(0, 11)+#limited-adult
  ylim(77, 81)+#limited-adult
  theme(
    # plot.title = element_text(size = 25),
    plot.margin = margin(.5, .5, .5, .5, "cm"),
    axis.text = element_text(size = 45),#30
    legend.position = "right", legend.key.size = unit(1, "cm"),
    legend.text = element_text(size = 30),
    legend.title = element_text(size = 35),
    text = element_text(family=fontfam),
    axis.title = element_text(size = 40)
    ) 
print(g1)


fig_name = paste('FlowOCT_',data_name,'_depth_',t_depth, '_', metric, '.pdf', sep = '')


ggsave(paste(figure_path,fig_name,sep = ""),device = "pdf", width = 16, height = 12, units =  "in")
}

```



```{r echo=TRUE, warning=FALSE}


```



