---
title: "Generating The Figures"
author: "Sina Aghaei"
date: "10/24/2020"
output: 
  # flexdashboard::flex_dashboard:
  #   orientation: columns
  html_document:
    # number_sections: true
 
---


In this script we provide the code for generating the figures in the paper.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE,warning = FALSE )
library(kableExtra)
library(png)
library(ggplot2)
library(reshape2)
library(egg)
require(tidyr)
require(dplyr)
library(dplyr)
library(latex2exp)
# library(ggpubr)
library(data.table)
library(RColorBrewer)
library(MASS)
require(scales)
rm(list=ls())

data_train_sp= read.csv('./../Results/Results archive/resupd.csv', header=TRUE, sep=',', na.strings="", stringsAsFactors =TRUE) 
data_train_csp= read.csv('./../Results/Results archive/res41.csv', header=TRUE, sep=',', na.strings="", stringsAsFactors =TRUE) 

forpres=TRUE
if (forpres){
  fontfam = "sans"
} else {
  fontfam = "serif"
}

figure_path = "./"


index <- data_train_sp$fair.bound == 0
data_train_sp$fair.bound[index] = 1

data_train_sp$sample <- as.factor(data_train_sp$sample)
data_train_sp$depth <- as.factor(data_train_sp$depth)
data_train_sp$fair.bound <- as.factor(data_train_sp$fair.bound)

data_train_csp$sample <- as.factor(data_train_csp$sample)
data_train_csp$depth <- as.factor(data_train_csp$depth)
data_train_csp$fair.bound <- as.factor(data_train_csp$fair.bound)

```

#Preparing Data
```{r echo=TRUE, warning=FALSE}
tmp_sp  <- data_train_sp
tmp_sp$fair.type = "SP"

tmp_sp <- tmp_sp %>%
  group_by(approach,data,depth, fair.type, fair.bound) %>%
  summarise(mean(train.acc),mean(sp.train.data), mean(sp.train.pred),mean(sp.train.pred),mean(sp.test.data),mean(sp.test.pred))

names(tmp_sp) <- c("approach","data","depth","fair.type","fair.bound","train.acc","train.data.fairness","train.pred.fairness","test.data.fairness","test.pred.fairness")


tmp_csp  <- data_train_csp
index <- tmp_csp$fair.bound == 0
tmp_csp$fair.bound[index] = 1
tmp_csp$fair.type = "CSP"

tmp_csp <- tmp_csp %>%
  group_by(approach,data,depth, fair.type, fair.bound) %>%
  summarise(mean(train.acc),mean(csp.train.data), mean(csp.train.pred),mean(csp.train.pred),mean(csp.test.data),mean(csp.test.pred))

names(tmp_csp) <- c("approach","data","depth","fair.type","fair.bound","train.acc","train.data.fairness","train.pred.fairness","test.data.fairness","test.pred.fairness")
tmp_csp <- subset(tmp_csp, tmp_csp$fair.bound != 0.5)

tmp <- rbind(tmp_sp,tmp_csp)
```



```{r echo=TRUE, warning=FALSE}
g1 <- ggplot(data = subset(tmp,tmp$depth==2), aes(x=(1-train.pred.fairness)*100, y=train.acc*100)) +
  geom_point(size=3)+
  geom_text(aes(label = fair.bound),
            vjust = "inward", hjust = "inward",check_overlap = TRUE, nudge_y = 1.5,
            show.legend = FALSE,size = 8) +
  geom_line( aes(linetype = fair.type, color = fair.type), size=2, color=brewer.pal(4, 'Set1')[3]) + 
  labs(x="Fairness (%)", y = "Accuracy (%)", linetype = "Constraint")+
  # ggtitle("Fairness vs Accuracy for various bounds")+
  theme(
    # plot.title = element_text(size = 25),
    axis.text = element_text(size = 25),
    legend.position = "right", legend.key.size = unit(1, "cm"),
    legend.text = element_text(size = 27),
    legend.title = element_text(size = 30),
    text = element_text(family=fontfam),
    axis.title = element_text(size = 29)
    )
print(g1)

if (forpres)
{
  ggsave(paste(figure_path,"sp.pdf",sep = ""),device = "pdf", width = 9, height = 5, units =  "in")
} else {
  ggsave(paste(figure_path,"sp.pdf",sep = ""),device = "pdf", width = 9, height = 5, units =  "in")
}

```


# 
```{r echo=TRUE, warning=FALSE}
g1 <- ggplot(data = subset(tmp_sp, tmp_sp$depth==2), aes(x=as.numeric(as.character(fair.bound)))) +
  geom_line( aes(y=train.acc), size=2, color=brewer.pal(4, 'Set1')[3]) + 
  geom_line( aes(y=1-train.pred.fairness), size=2, color=brewer.pal(4, 'Set1')[2]) +
  scale_y_continuous(
    # Features of the first axis
    name = "Train Acc",
    # Add a second axis and specify its features
    sec.axis = sec_axis(~.*1, name="Train SP")
  ) +
  theme(legend.position = "right",text = element_text(size=14,family=fontfam)) 
print(g1)

if (forpres)
{
  ggsave(paste(figure_path,"sp.pdf",sep = ""),device = "pdf", width = 5, height = 3.3, units =  "in")
} else {
  ggsave(paste(figure_path,"sp.pdf",sep = ""),device = "pdf", width = 5, height = 3.3, units =  "in")
}

```
