---
title: "Generating The Figures"
author: "Sina Aghaei"
date: "10/24/2020"
output: 
  # flexdashboard::flex_dashboard:
  #   orientation: columns
  html_document:
    # number_sections: true
 
---


In this script we provide the code for generating the figures in the paper.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,message = FALSE,warning = FALSE )
library(kableExtra)
library(png)
library(ggplot2)
library(reshape2)
library(egg)
require(tidyr)
require(dplyr)
library(dplyr)
library(latex2exp)
# library(ggpubr)
library(data.table)
library(RColorBrewer)
library(MASS)
require(scales)
rm(list=ls())

data= read.csv('./../Results/FairOCT_Compass_10800_May_20.csv', header=TRUE, sep=',', na.strings="", stringsAsFactors =TRUE) 


forpres=TRUE
if (forpres){
  fontfam = "sans"
} else {
  fontfam = "serif"
}

figure_path = "./"


data$sample <- as.factor(data$sample)
data$depth <- as.factor(data$depth)
data$fair.type <- as.factor(data$fair.type)
data$fair.bound <- as.factor(data$fair.bound)


# index <- data$fair.bound %in% c(0.05, 0.1, 0.2, 0.4,0.5,0.6,1)
# data <- data[index,]

for(i in c('SP','CSP','PE','EOpp','EOdds')){
  tmp_none <- data[data$fair.type == 'None',]
  tmp_none$fair.type = i
  data = rbind(data,tmp_none)
}

data <- data[data$fair.type!= 'None',]
rm(tmp_none)
```

#Preparing Data
```{r echo=TRUE, warning=FALSE}
tmp <- data

tmp <- tmp %>%
  group_by(approach,data,depth, fair.type, fair.bound) %>%
  summarise(mean(train.acc),mean(test.acc),mean(sp.train.data), mean(sp.train.pred),
            mean(sp.test.data),mean(sp.test.pred),
            mean(csp.train.data), mean(csp.train.pred),
            mean(csp.test.data),mean(csp.test.pred),
            mean(pe.train.pred),
            mean(pe.test.pred),
            mean(EOpp.train.pred),
            mean(EOpp.test.pred),
            mean(EOdds.train.pred),
            mean(EOdds.test.pred))

names(tmp) <- c("approach","data","depth","fair.type","fair.bound","train.acc",'test.acc',
                   "train.data.sp","train.pred.sp","test.data.sp","test.pred.sp",
                   "train.data.csp","train.pred.csp","test.data.csp","test.pred.csp",
                   "train.pred.pe","test.pred.pe",
                   "train.pred.EOpp","test.pred.EOpp",
                   "train.pred.EOdds","test.pred.EOdds")


# tmp <- tmp[c("approach","data","depth","fair.type","fair.bound","train.acc",
#              'train.pred.sp','train.pred.csp','train.pred.pe','train.pred.EOpp','train.pred.EOdds')]
# 
# tmp <- melt(tmp, id.vars=c("approach","data","depth","fair.type","fair.bound",'train.acc'))

tmp <- tmp[c("approach","data","depth","fair.type","fair.bound","test.acc",
             'test.pred.sp','test.pred.csp','test.pred.pe','test.pred.EOpp','test.pred.EOdds')]

tmp <- melt(tmp, id.vars=c("approach","data","depth","fair.type","fair.bound",'test.acc'))


tmp$fair.type <- factor(tmp$fair.type, levels = c('SP','CSP','PE','EOpp','EOdds'))
# levels(tmp$fair.type) <- c('SP Constraint','CSP Constraint','PE Constraint','EOpp Constraint','EOdds Constraint')

# tmp$variable <- factor(tmp$variable, levels = c('train.pred.sp','train.pred.csp','train.pred.pe','train.pred.EOpp','train.pred.EOdds'))
tmp$variable <- factor(tmp$variable, levels = c('test.pred.sp','test.pred.csp','test.pred.pe','test.pred.EOpp','test.pred.EOdds'))

tmp$fair.bound <- as.numeric(as.character(tmp$fair.bound))
```


# Facet grid figures

```{r echo=TRUE, warning=FALSE}
g1 <- ggplot(data = subset(tmp,tmp$depth ==2), aes(x=(1-value)*100, y=test.acc*100)) +
  geom_point(aes(color = fair.bound,size=0.5))+#aes(size = fair.bound)
  scale_color_gradient(low="blue", high="red")+
  # geom_text(aes(label = fair.bound),
  #           vjust = "inward", hjust = "inward",check_overlap = TRUE, nudge_y = 5,nudge_x = 4,
  #           show.legend = FALSE,size = 3) +
  geom_line() + 
  facet_grid(vars(fair.type), vars(variable))+
  labs(x="Fairness (%)", y = "Accuracy (%)", linetype = "Constraint")+
  theme(
    # plot.title = element_text(size = 25),
    axis.title = element_text(size = 29),
    axis.text = element_text(size = 15),
    axis.text.x = element_text(angle = 90),
    legend.position = "right", legend.key.size = unit(1, "cm"),
    legend.text = element_text(size = 23),
    legend.title = element_text(size = 26),
    strip.text = element_text(size = 20)
    )+
    guides(size = "none")
print(g1)

if (forpres)
{
  ggsave(paste(figure_path,"grid_test.pdf",sep = ""),device = "pdf", width = 16, height = 11, units =  "in")
} else {
  ggsave(paste(figure_path,"grid_train.pdf",sep = ""),device = "pdf", width = 16, height = 11, units =  "in")
}

```


```{r echo=TRUE, warning=FALSE}
g1 <- ggplot(data = subset(tmp,tmp$fair.type=='EOdds' & tmp$depth ==2), aes(x=(1-value)*100, y=train.acc*100)) +
  geom_point(size=3)+
  geom_text(aes(label = fair.bound),
            vjust = "inward", hjust = "inward",check_overlap = TRUE, nudge_y = 1.4,
            show.legend = FALSE,size = 4) +
  geom_line( aes(color = variable), size=2) + 
  labs(x="Fairness (%)", y = "Accuracy (%)", linetype = "Constraint")+
  # ggtitle("Fairness vs Accuracy for various bounds")+
  theme(
    # plot.title = element_text(size = 25),
    axis.text = element_text(size = 25),
    legend.position = "right", legend.key.size = unit(1, "cm"),
    legend.text = element_text(size = 27),
    legend.title = element_text(size = 30),
    text = element_text(family=fontfam),
    axis.title = element_text(size = 29)
    ) 
print(g1)

if (forpres)
{
  ggsave(paste(figure_path,"eodds.pdf",sep = ""),device = "pdf", width = 12, height = 8, units =  "in")
} else {
  ggsave(paste(figure_path,"eodds.pdf",sep = ""),device = "pdf", width = 12, height = 8, units =  "in")
}

```


